# -*- coding: utf-8 -*-
"""llm_helper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UbmZ4hDx1xIOZHhzEw8p9SXgA_QEGTAx
"""

# -*- coding: utf-8 -*-
"""llm_helper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UbmZ4hDx1xIOZHhzEw8p9SXgA_QEGTAx
"""

import os
from dotenv import load_dotenv

# Load variables from the .env file
load_dotenv() 

# Inject your OpenRouter Key into the environment
os.environ["OPENROUTER_API_KEY"] = os.getenv("OPENROUTER_API_KEY")
print("✅ OpenRouter key loaded!")

from openai import OpenAI
from langchain_text_splitters import RecursiveCharacterTextSplitter


# Initialize client directed to OpenRouter
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key= os.environ["OPENROUTER_API_KEY"]
)

def LLM_call(prompt: str):
    try:
        response = client.chat.completions.create(
            model="nvidia/nemotron-3-ultra-550b-a55b:free",
            max_tokens=400,  # Slightly higher to ensure it has room to start typing
            messages=[
                {"role": "user", "content": prompt}
            ]
        )

        # Extract message safely
        output_text = response.choices[0].message.content

        if output_text and output_text.strip():
            return output_text
        else:
            return "⚠️ Warning: The model returned a blank or empty string."
    except Exception as e:
        return f"❌ Execution failed: {e}"

def LLM_enrich(prompt: str):
    try:
        response = client.chat.completions.create(
            model="nvidia/nemotron-3-ultra-550b-a55b:free",
            max_tokens=160,
            extra_body={
                "reasoning": {
                    "effort": "low", # Can be "none", "low", "medium", or "high"
                    "exclude_from_response": True # Hides the raw reasoning from final output
                }
            },
            messages=[
                {"role":"user", "content": prompt}
            ],
            temperature=0.0 # Completely based on chunk
            )
        return response
    except Exception as e:
        print(f"API Error: {e}")
        return None  # Return None instead of a string

def get_embedding(text: str):
    response = client.embeddings.create(
        model="openai/text-embedding-3-small",
        input=[text],
        encoding_format="float"
    )
    # Extract the nested vector correctly from the data array
    return response.data[0].embedding

def semantic_search(query: str, db: list):
    query_vector = get_embedding(query)
    best_match = None
    highest_score = -1

    for item in db:
        score = sum(a * b for a, b in zip(query_vector, item["vector"]))
        if score > highest_score:
            highest_score = score
            best_match = item["text"]
    return best_match

def enrich_context(raw: str, chunk: str):
    prompt = """
    <document>
    {}
    </document>
    Here is the chunk we want to situate within the whole document
    <chunk>
    {}
    </chunk>
    Please give a short succinct context to situate this chunk within the overall document for the purposes of improving search retrieval of the chunk. Answer only with the succinct context and nothing else.""".format(raw, chunk)
    # Prompt designed to leverage Prompt Caching
    # LLM returns chunk's summarised context
    response = LLM_enrich(prompt)

    # Safely check if response is a valid API object, not None
    if response and hasattr(response, 'choices') and response.choices:
        output_context = response.choices[0].message.content.strip()
        return f"{output_context}\n{chunk}"

    return chunk  # Safely fall back to original chunk if API failed