# -*- coding: utf-8 -*-
"""SimpleRAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tlG5dSBHICTHR6YOsHborKf-31qcrefn

Install dependencies:

pip install openai -q
pip install langchain-text-splitters -q
pip install streamlit -q
pip install pyngrok -q
pip install python-dotenv -q

"""
import LLM_Helper
import streamlit as st

st.title("hke rag lvl1")
st.write("demo")

# 1. Initialize session states
if "vector_db" not in st.session_state:
    st.session_state.vector_db = []

if "messages" not in st.session_state:
    st.session_state.messages = []

# 2. Define processing logic in a callback
def process_and_embed(file_text):
    with st.status("Adding context and embedding...", expanded=False) as status:
        splitter = LLM_Helper.RecursiveCharacterTextSplitter(
            chunk_size=500,
            chunk_overlap=50,
            separators=["\n\n", "\n", ". ", " ", ""]
        )
        chunks = splitter.split_text(file_text)

        for i in range(len(chunks)):
            # Save enriched text to session state to make it persistent
            enriched_chunk = LLM_Helper.enrich_context(file_text, chunks[i])
            st.session_state.vector_db.append({
                "text": enriched_chunk,
                "vector": LLM_Helper.get_embedding(enriched_chunk)
            })
        # Append to vector store
        status.update(expanded=False, state="complete")
    status.update(state="complete")

    # Display only the toast message
    st.toast("Document embedded successfully!", icon="✅")

    st.session_state.upload_success = True

# 3. File Uploader UI
uploaded_file = st.file_uploader("Upload Reference File (.txt)", type=["txt"])

if uploaded_file is not None:
    file_contents = uploaded_file.read().decode("utf-8")
    st.success("File uploaded successfully!")

    with st.expander("View file content"):
        st.text(file_contents)

    # 4. Action Button
    st.button(
        "Add to Database",
        on_click=process_and_embed,
        args=(file_contents,)
    )

    # Fixed: Displays the persistent session state variable
    if st.session_state.vector_db:
        with st.expander("View enriched text"):
            all_enriched_texts = [item["text"] for item in st.session_state.vector_db]

            # Join them cleanly with a visual separator
            st.text("\n\n---\n\n".join(all_enriched_texts))

# 5. Display persistent success message
if st.session_state.get("upload_success"):
    st.toast("Database updated successfully!")


# persistent chat history
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.write(message["content"])

# Accept user input prompt
if query := st.chat_input("Ask a question about your documents..."):

    # 1. Display user message in chat message container
    st.session_state.messages.append({"role": "user", "content": query})
    with st.chat_message("user"):
        st.write(query)

    # 2. Display assistant response placeholder
    with st.chat_message("assistant"):

        # Check if documents have been embedded first
        if not st.session_state.vector_db:
            error_msg = "Please upload and embed a document first!"
            st.warning(error_msg)
            st.session_state.messages.append({"role": "assistant", "content": error_msg})
        else:
            with st.spinner("Searching knowledge base and generating answer..."):

                # --- RETRIEVAL LOGIC ---
                context = LLM_Helper.semantic_search(query,st.session_state.vector_db)
                full_prompt = f"Context: {context}\n\nQuestion: {query}\nAnswer the question using only the context."
                response = LLM_Helper.LLM_call(full_prompt)
                st.write(response)

                # 3. Save assistant response to session state history
                st.session_state.messages.append({"role": "assistant", "content": response})"""
                

